[package]
name = "makai_llm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
dotenvy = "0.15.7"
llm = "1.3.4"
rand = "0.9.2"
serenity = "0.12.4"
tokio = "1.48.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

